import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as ts from "typescript-compiler-api";

const packageRoot = path.dirname(dirname(fileURLToPath(import.meta.url)));
const inputPath = path.join(packageRoot, "src", "index.ts");
const outputPath = path.join(packageRoot, "generated", "types.ts");
const configPath = path.join(packageRoot, "tsconfig.json");

function dirname(filePath) {
	return path.dirname(filePath);
}

function readConfig() {
	const config = ts.readConfigFile(configPath, ts.sys.readFile);

	if (config.error) {
		throw new Error(
			ts.flattenDiagnosticMessageText(config.error.messageText, "\n"),
		);
	}

	return ts.parseJsonConfigFileContent(
		config.config,
		ts.sys,
		packageRoot,
		undefined,
		configPath,
	);
}

function formatDiagnostics(diagnostics) {
	return ts.formatDiagnosticsWithColorAndContext(diagnostics, {
		getCanonicalFileName: (fileName) => fileName,
		getCurrentDirectory: () => packageRoot,
		getNewLine: () => "\n",
	});
}

function isExportedTypeAlias(statement) {
	return (
		ts.isTypeAliasDeclaration(statement) &&
		statement.modifiers?.some(
			(modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword,
		)
	);
}

const parsedConfig = readConfig();
const program = ts.createProgram({
	rootNames: parsedConfig.fileNames,
	options: parsedConfig.options,
});
const diagnostics = ts.getPreEmitDiagnostics(program);

if (diagnostics.length > 0) {
	throw new Error(formatDiagnostics(diagnostics));
}

const sourceFile = program.getSourceFile(inputPath);

if (!sourceFile) {
	throw new Error(`Could not find source file: ${inputPath}`);
}

const checker = program.getTypeChecker();
const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
const typeNodeFlags =
	ts.NodeBuilderFlags.NoTruncation |
	ts.NodeBuilderFlags.MultilineObjectLiterals |
	ts.NodeBuilderFlags.UseSingleQuotesForStringLiteralType;
const typeFormatFlags =
	ts.TypeFormatFlags.NoTruncation |
	ts.TypeFormatFlags.MultilineObjectLiterals |
	ts.TypeFormatFlags.UseSingleQuotesForStringLiteralType;

function typeToTypeNode(type, statement) {
	if (type.isUnion()) {
		const typeNodes = type.types
			.map((part) => checker.typeToTypeNode(part, statement, typeNodeFlags))
			.filter(Boolean);

		if (typeNodes.length === type.types.length) {
			return ts.factory.createUnionTypeNode(typeNodes);
		}
	}

	return checker.typeToTypeNode(type, statement, typeNodeFlags);
}

function objectTypeToTypeLiteral(type, statement) {
	const properties = type.getProperties();

	if (properties.length === 0) {
		return undefined;
	}

	const members = properties
		.map((property) => {
			const declaration =
				property.valueDeclaration ?? property.declarations?.[0];
			const propertyType = checker.getTypeOfSymbolAtLocation(
				property,
				declaration ?? statement,
			);
			const propertyTypeNode = typeToTypeNode(propertyType, statement);

			if (!propertyTypeNode) {
				return undefined;
			}

			return ts.factory.createPropertySignature(
				undefined,
				property.name,
				property.flags & ts.SymbolFlags.Optional
					? ts.factory.createToken(ts.SyntaxKind.QuestionToken)
					: undefined,
				propertyTypeNode,
			);
		})
		.filter(Boolean);

	if (members.length !== properties.length) {
		return undefined;
	}

	return ts.factory.createTypeLiteralNode(members);
}

const aliases = sourceFile.statements
	.filter(isExportedTypeAlias)
	.map((statement) => {
		const type = checker.getTypeFromTypeNode(statement.type);
		let typeNode = typeToTypeNode(type, statement);

		if (!typeNode) {
			const typeText = checker.typeToString(type, statement, typeFormatFlags);

			return `export type ${statement.name.text} = ${typeText};`;
		}

		const alias = ts.factory.createTypeAliasDeclaration(
			[ts.factory.createModifier(ts.SyntaxKind.ExportKeyword)],
			statement.name.text,
			undefined,
			typeNode,
		);

		const printed = printer.printNode(
			ts.EmitHint.Unspecified,
			alias,
			sourceFile,
		);

		if (
			printed === `export type ${statement.name.text} = ${statement.name.text};`
		) {
			typeNode = objectTypeToTypeLiteral(type, statement) ?? typeNode;
			const expandedAlias = ts.factory.createTypeAliasDeclaration(
				[ts.factory.createModifier(ts.SyntaxKind.ExportKeyword)],
				statement.name.text,
				undefined,
				typeNode,
			);

			return printer.printNode(
				ts.EmitHint.Unspecified,
				expandedAlias,
				sourceFile,
			);
		}

		return printed;
	});

const output = `// Generated by pnpm --filter type-inference types:write
// Source: type-inference/src/hover.ts

${aliases.join("\n\n")}
`;

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, output);

console.log(
	`Wrote ${path.relative(path.dirname(packageRoot), outputPath).replaceAll(path.sep, "/")}`,
);
