packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  lefthook: set this to true or false
  sharp: set this to true or false
minimumReleaseAgeExclude:
  - '@contract-first-api/core@4.2.1'
  - '@contract-first-api/express@4.2.0'
  - '@contract-first-api/openapi@1.0.1'
  - '@contract-first-api/api-client@4.1.0'
  - '@contract-first-api/react-query@4.1.0'
